export enum PermissionEnum {
    READ_USERS = 'read:users',
    CREATE_USERS = 'create:users',
    UPDATE_USERS = 'update:users',
    DELETE_USERS = 'delete:users',
    READ_ROLES = 'read:roles',
    CREATE_ROLES = 'create:roles',
    UPDATE_ROLES = 'update:roles',
    DELETE_ROLES = 'delete:roles',
    READ_PERMISSIONS = 'read:permissions',
    CREATE_PERMISSIONS = 'create:permissions',
    UPDATE_PERMISSIONS = 'update:permissions',
    DELETE_PERMISSIONS = 'delete:permissions',
    ASSIGN_PERMISSIONS = 'assign:permissions',
    ASSIGN_ROLES = 'assign:roles',
    SEED_DATA = 'seed:data',
}